language: java

jdk:
  - openjdk11

install: true

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assemble testClasses
